package com.newsuper.t.consumer.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.newsuper.t.consumer.bean.GoodsDbBean;

import com.newsuper.t.consumer.greendao.GoodsDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDbBeanDaoConfig;

    private final GoodsDbBeanDao goodsDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDbBeanDaoConfig = daoConfigMap.get(GoodsDbBeanDao.class).clone();
        goodsDbBeanDaoConfig.initIdentityScope(type);

        goodsDbBeanDao = new GoodsDbBeanDao(goodsDbBeanDaoConfig, this);

        registerDao(GoodsDbBean.class, goodsDbBeanDao);
    }
    
    public void clear() {
        goodsDbBeanDaoConfig.clearIdentityScope();
    }

    public GoodsDbBeanDao getGoodsDbBeanDao() {
        return goodsDbBeanDao;
    }

}
